seed: 1919
wandb:
  group: "AAN"
  name: "norm-attention"
  key: "58d1b0b4e77ad3dd9ebd08eb490255e83aa70bfe"
  entity: "ssm-eth"
  project: "neurips-2024-new"
dataset:
  name: "AAN"
  _name_: "aan"
  data_dir: "/cluster/scratch/jsieber/aan"
  n_workers: 8
train:
  num_epochs: 30
  batch_size: 8
  lr: 0.0005
  wd: 0.1
  warmup: 5
model:
  # task specific dims
  input_dim: 1
  output_dim: 2
  # backbone model
  layer: "transformer"
  attention_fn: "norm-attention"
  norm_fn: "exp"
  num_layers: 6
  hidden_dim: 128
  state_dim: 128
  num_heads: 4
  att_dropout: 0.0
  norm: "layer"
  # embedding & positional embedding
  embedding: True
  vocab_size: 98
  max_pos_embed: 4096
  # mlp
  mlp_dim: 512
  # global dropout rate
  dropout: 0.1
  # classifier
  classifier: True
  pooling: "mean"
  # use dual classification
  dual: True
