seed: 1919
dataset:
  name: "AAN"
  _name_: "aan"
train:
  num_epochs: 30
  batch_size: 32
  lr: 0.0002
  wd: 0.01
  dropout: 0.0
model:
  num_blocks: 6
  input_dim: 1
  output_dim: 2
  hidden_dim: 128
  state_dim: 64
  conv_dim: 4
  expansion: 2
  glu: True
  norm: "layer"
  prenorm: False
  pooling: "mean"