seed: 1919
wandb:
  group: "CIFAR10"
  name: "norm-attention"
  key: "58d1b0b4e77ad3dd9ebd08eb490255e83aa70bfe"
  entity: "ssm-eth"
  project: "neurips-2024-new"
dataset:
  name: "CIFAR-10"
  _name_: "cifar"
  grayscale: True
  tokenize: True
train:
  num_epochs: 50
  batch_size: 64
  lr: 0.001
  wd: 0.0
  warmup: 5
model:
  # task specific dims
  input_dim: 1
  output_dim: 10
  # backbone model
  layer: "transformer"
  attention_fn: "norm-attention"
  norm_fn: "exp"
  num_layers: 2
  hidden_dim: 128
  state_dim: 64
  num_heads: 8
  att_dropout: 0.1
  norm: "layer"
  # embedding & positional embedding
  # WARNING: make sure to set dataset.tokenize to True
  embedding: True
  vocab_size: 256 # discrete byte inputs
  max_pos_embed: 1024 # 0 means no positional encoding; otherwise length of input (1024)
  # mlp
  mlp_dim: 128
  # global dropout rate
  dropout: 0.1
  # classifier
  classifier: True
  pooling: "mean"
  # use dual classification
  dual: False
