seed: 1919
save: True
wandb:
  group: "CIFAR10"
  name: "SSD - Mamba-2"
  key: "58d1b0b4e77ad3dd9ebd08eb490255e83aa70bfe"
  entity: "ssm-eth"
  project: "neurips-2024"
dataset:
  name: "CIFAR-10"
  _name_: "cifar"
  grayscale: True
train:
  num_epochs: 50
  batch_size: 64
  lr: 0.0002
  wd: 0.01
  warmup: 5
model:
  layer: "mamba"
  version: "mamba2"
  num_layers: 2
  input_dim: 1
  output_dim: 10
  hidden_dim: 128
  state_dim: 64
  conv_dim: 4
  expansion: 1
  dropout: 0.0
  glu: True
  norm: "layer"
  dual: False
  prenorm: False
  lambd: -1.0
  pooling: "mean"
  embedding: True
