seed: 1919
wandb:
  key: "58d1b0b4e77ad3dd9ebd08eb490255e83aa70bfe"
  entity: "ssm-eth"
  project: "lra-benchmark"
dataset:
  name: "IMDB"
  _name_: "imdb"
  fixed_size: True
train:
  num_epochs: 100
  batch_size: 32
  lr: 0.00025
  wd: 0.01
model:
  layer: "hawk"
  num_blocks: 6
  input_dim: 1
  output_dim: 2
  hidden_dim: 128
  kernel_size: 4
  expansion: 1.5
  gmlp_expansion: 1
  dropout: 0.0
  init: "exp"
  dual: False
  pooling: "mean"
