seed: 1919
wandb:
  key: "58d1b0b4e77ad3dd9ebd08eb490255e83aa70bfe"
  entity: "ssm-eth"
  project: "lra-benchmark"
dataset:
  name: "IMDB"
  _name_: "imdb"
train:
  num_epochs: 100
  batch_size: 32
  lr: 0.0005
  wd: 0.01
model:
  layer: "mamba"
  num_blocks: 6
  input_dim: 1
  output_dim: 2
  hidden_dim: 64
  state_dim: 64
  conv_dim: 4
  expansion: 2.5
  dropout: 0.0
  glu: True
  norm: "layer"
  dual: False
  prenorm: True
  pooling: "mean"
