seed: 1919
dataset:
  name: "IMDB"
  _name_: "imdb"
  fixed_size: True
train:
  num_epochs: 50
  batch_size: 32
  lr: 0.0005
  wd: 0.01
  dropout: 0.0
model:
  layer: "griffin"
  num_blocks: 6
  input_dim: 1
  output_dim: 2
  hidden_dim: 128
  kernel_size: 4
  expansion: 2
  gmlp_expansion: 2
  pooling: "mean"