seed: 1919
wandb:
  group: "ListOps"
  name: "sm-attention"
  key: "58d1b0b4e77ad3dd9ebd08eb490255e83aa70bfe"
  entity: "ssm-eth"
  project: "neurips-2024-new"
dataset:
  name: "LISTOPS"
  _name_: "listops"
train:
  num_epochs: 50
  batch_size: 8
  lr: 0.0005
  wd: 0.1
  warmup: 5
model:
  # task specific dims
  input_dim: 1
  output_dim: 10
  # backbone model
  layer: "transformer"
  attention_fn: "sm-attention"
  num_layers: 8
  hidden_dim: 128
  state_dim: 64
  num_heads: 8
  att_dropout: 0.1
  norm: "layer"
  # embedding & positional embedding
  embedding: True
  vocab_size: 18
  max_pos_embed: 2048
  # mlp
  mlp_dim: 512
  # global dropout rate
  dropout: 0.1
  # classifier
  classifier: True
  pooling: "mean"
  # use dual classification
  dual: False
