seed: 1919
wandb:
  key: "58d1b0b4e77ad3dd9ebd08eb490255e83aa70bfe"
  entity: "ssm-eth"
  project: "lra-benchmark"
dataset:
  name: "LISTOPS"
  _name_: "listops"
train:
  num_epochs: 50
  batch_size: 64
  lr: 0.0001
  wd: 0.01
model:
  layer: "mamba"
  num_blocks: 10
  input_dim: 1
  output_dim: 10
  hidden_dim: 64
  state_dim: 64
  conv_dim: 4
  expansion: 3
  dropout: 0.0
  glu: True
  norm: "layer"
  dual: False
  prenorm: False
  pooling: "mean"
