seed: 1919
dataset:
  name: "LISTOPS"
  _name_: "listops"
  fixed_size: True
train:
  num_epochs: 50
  batch_size: 32
  lr: 0.0001
  wd: 0.01
  dropout: 0.0
model:
  num_blocks: 6
  input_dim: 1
  output_dim: 10
  hidden_dim: 128
  kernel_size: 4
  expansion: 2
  gmlp_expansion: 2
  pooling: "mean"