seed: 1919
dataset:
  name: "Pathfinder-128"
  _name_: "pathfinder"
  resolution: 128
  data_dir: "/cluster/scratch/jsieber/pathfinder/pathfinder128"
train:
  num_epochs: 50
  batch_size: 64
  lr: 0.0001
  wd: 0.01
  dropout: 0.0
model:
  layer: "mamba"
  num_blocks: 6
  input_dim: 1
  output_dim: 2
  hidden_dim: 128
  state_dim: 64
  conv_dim: 4
  expansion: 2
  glu: True
  norm: "layer"
  prenorm: True
  dual: False
  pooling: "mean"
