seed: 1919
wandb:
  key: "58d1b0b4e77ad3dd9ebd08eb490255e83aa70bfe"
  entity: "ssm-eth"
  project: "lra-benchmark"
dataset:
  name: "Pathfinder-32"
  _name_: "pathfinder"
  resolution: 32
  data_dir: "/cluster/scratch/jsieber/pathfinder/pathfinder32"
train:
  num_epochs: 100
  batch_size: 32
  lr: 0.0001
  wd: 0.01
model:
  layer: "mamba"
  num_blocks: 6
  input_dim: 1
  output_dim: 2
  hidden_dim: 128
  state_dim: 64
  conv_dim: 4
  expansion: 4
  dropout: 0.0
  glu: True
  norm: "layer"
  prenorm: True
  dual: False
  pooling: "mean"
