seed: 1919
dataset:
  name: "Pathfinder-32"
  _name_: "pathfinder"
  resolution: 32
  data_dir: "data/pathfinder/pathfinder32"
train:
  num_epochs: 50
  batch_size: 32
  lr: 0.0002
  wd: 0.0
  dropout: 0.1
model:
  num_blocks: 6
  input_dim: 1
  output_dim: 2
  hidden_dim: 128
  state_dim: 64
  conv_dim: 4
  expansion: 2
  glu: True
  norm: "layer"
  prenorm: True
  pooling: "mean"