seed: 1919
dataset:
  name: "Pathfinder-32"
  _name_: "pathfinder"
  resolution: 128
  data_dir: "/cluster/scratch/jsieber/pathfinder/pathfinder128"
train:
  num_epochs: 50
  batch_size: 32
  lr: 0.0001
  wd: 0.0
model:
  layer: "griffin"
  num_blocks: 6
  input_dim: 1
  output_dim: 2
  hidden_dim: 128
  kernel_size: 4
  expansion: 2
  gmlp_expansion: 2
  dual: False
  pooling: "mean"