seed: 1919
dataset:
  name: "Pathfinder-128"
  _name_: "pathfinder"
  resolution: 128
train:
  num_epochs: 50
  batch_size: 32
  lr: 0.0001
  wd: 0.0
  dropout: 0.0
model:
  num_blocks: 6
  input_dim: 1
  output_dim: 2
  hidden_dim: 128
  state_dim: 64
  conv_dim: 4
  expansion: 2
  prenorm: True
  pooling: "mean"